### ISSUE TITLE
issue in BraintreeBrowserSwitchActivity

### ISSUE THREAD

**Issue by chauhan-saurabh** [jibon57/nativescript-braintree#1]
I have a issue :
BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration

**Comment by chauhan-saurabh** [comment]
its my android manifest.xml


<supports-screens
	android:smallScreens="true"
	android:normalScreens="true"
	android:largeScreens="true"
	android:xlargeScreens="true"/>

<uses-sdk
	android:minSdkVersion="17"
	android:targetSdkVersion="__APILEVEL__"/>

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.INTERNET"/>

<application
	android:name="com.tns.NativeScriptApplication"
	android:allowBackup="true"
	android:icon="@drawable/icon"
	android:label="@string/app_name"
	android:theme="@style/AppTheme">

	<activity
		android:name="com.tns.NativeScriptActivity"
		android:label="@string/title_activity_kimera"
		android:configChanges="keyboardHidden|orientation|screenSize"
		android:theme="@style/LaunchScreenTheme">

		<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

		<intent-filter>
			<action android:name="android.intent.action.MAIN" />
			<category android:name="android.intent.category.LAUNCHER" />
		</intent-filter>
	</activity>
	<activity android:name="com.tns.ErrorReportActivity"/>
	<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
		android:launchMode="singleTask">
		<intent-filter>
			<action android:name="android.intent.action.VIEW" ></action>
			<category android:name="android.intent.category.DEFAULT" ></category>
			<category android:name="android.intent.category.BROWSABLE" ></category>
			<data android:scheme="org.nativescript.shyft.braintree" ></data>
		</intent-filter>
	</activity>
</application>

**Comment by chauhan-saurabh** [comment]
its my app.gradle

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "org.nativescript.shyft"  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  compileSdkVersion 26
  buildToolsVersion "26.0.1"
}

allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
    }
}

dependencies {
	compile 'com.braintreepayments.api:drop-in:3.+'
}

**Comment by jibon57** [comment]
@chauhan-saurabh Please try to remove extra code from your `manifest.xml` file & try. If possible start a new project & follow the plugin's instruction step by step. You don't need to edit your `manifest.xml` file.

**Comment by chauhan-saurabh** [comment]
@jibon57  but its  not possible for me to start a new project

**Comment by jibon57** [comment]
Try to remove the extra code u have addes in manifast.xml file & try again.

**Comment by chauhan-saurabh** [comment]
@jibon here is the error in IOS

[BraintreeSDK] CRITICAL PayPal requires [BTAppSwitch setReturnURLScheme:] to be configured to begin with your app's bundle ID (org.nativescript.shyft). Currently, it is set to (org.nativescript.shyft).

**Comment by chauhan-saurabh** [comment]
requires and current bundle url is same but error exists why??

**Comment by jibon57** [comment]
Have you followed this: https://github.com/jibon57/nativescript-braintree/blob/master/README.md#2-ios-problem-with-paypal--venmo?

Past here the respective codes.

**Comment by chauhan-saurabh** [comment]
its my shyft.plist

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>NSCameraUsageDescription</key>
    <string>Requires access to camera.</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>com.venmo.touch.v2</string>
      <string>com.paypal.ppclient.touch.v1</string>
      <string>com.paypal.ppclient.touch.v2</string>
    </array>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Requires access to photo library.</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>Requires access to microphone.</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Need location when in use.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Need location always.</string>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>${PRODUCT_NAME}</string>
    <key>CFBundleExecutable</key>
    <string>${EXECUTABLE_NAME}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${PRODUCT_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>
    <key>UIRequiresFullScreen</key>
    <true/>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
      <string>armv7</string>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>CFBundleIdentifier</key>
    <string>org.nativescript.shyft</string>
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>org.nativescript.shyft</string>
            </array>
        </dict>
    </array>
    <key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>orgnativescriptShyft</string>
        </array>
      </dict>
    </array>
  </dict>
</plist>

**Comment by chauhan-saurabh** [comment]
hello @jibon57 I am sharing u respective files

**Comment by chauhan-saurabh** [comment]
![screen shot 2017-09-26 at 9 53 48 am](https://user-images.githubusercontent.com/31333681/30842149-e5c1101a-a29d-11e7-9b04-59225a430db3.png)


its my shyft.plist

**Comment by chauhan-saurabh** [comment]
and its my main.ts


// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import * as app from "application";
declare var UIResponder, UIApplicationDelegate, BTAppSwitch;

import { AppModule } from "./app.module";


if (app.ios) {
    
        class MyDelegate extends UIResponder {
    
            public static ObjCProtocols = [UIApplicationDelegate];
    
            applicationDidFinishLaunchingWithOptions(application, launchOptions): boolean {
    
                try {
                    BTAppSwitch.setReturnURLScheme("org.nativescript.shyft"); // should be same as CFBundleURLSchemes value.
                    return true;
                } catch (error) {
                    console.log(error);
                }
                return false;
            }
    
            applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {
    
                try {
                    if (url.scheme == "org.nativescript.shyft") {
                        BTAppSwitch.handleOpenURLSourceApplication(url, sourceApplication);
                        return true;
                    }
                } catch (error) {
                    console.log(error);
                }
                return false;
            }
        }
        
        app.ios.delegate = MyDelegate;
    }

    platformNativeScriptDynamic().bootstrapModule(AppModule);

**Comment by jibon57** [comment]
@chauhan-saurabh You haven't followed https://github.com/jibon57/nativescript-braintree/blob/master/README.md#2-ios-problem-with-paypal--venmo perfectly.

`org.nativescript.shyft` this is wrong. It should be something like `org.nativescript.shyft.payment` or `org.nativescript.shyft.anythingelse`. Please read the instruction carefully.

**Comment by chauhan-saurabh** [comment]
ohs @jibon57

**Comment by chauhan-saurabh** [comment]
hello @jibon57  I have a new issue 

[BraintreeSDK] CRITICAL PayPal requires a return URL scheme to be configured via [BTAppSwitch setReturnURLScheme:]. This custom URL scheme must also be registered with your app.

**Comment by chauhan-saurabh** [comment]
![screen shot 2017-09-26 at 11 12 17 am](https://user-images.githubusercontent.com/31333681/30843746-d3bde52c-a2a8-11e7-924f-faa7fa9e2599.png

**Comment by jibon57** [comment]
@chauhan-saurabh Please follow everything step by step. You haven't added your url to `plist` file.

**Comment by chauhan-saurabh** [comment]
if (app.ios) {
    
        class MyDelegate extends UIResponder {
    
            public static ObjCProtocols = [UIApplicationDelegate];
    
            applicationDidFinishLaunchingWithOptions(application, launchOptions): boolean {
    
                try {
                    BTAppSwitch.setReturnURLScheme("org.nativescript.shyft.payment"); // should be same as CFBundleURLSchemes value.
                    return true;
                } catch (error) {
                    console.log(error);
                }
                return false;
            }
    
            applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {
    
                try {
                    if (url.scheme == "org.nativescript.shyft.payment") {
                        BTAppSwitch.handleOpenURLSourceApplication(url, sourceApplication);
                        return true;
                    }
                } catch (error) {
                    console.log(error);
                }
                return false;
            }
        }
        
        app.ios.delegate = MyDelegate;
    }

**Comment by chauhan-saurabh** [comment]
I already send you my plist screenshot

**Comment by jibon57** [comment]
Try
`tns platform remove ios`
`tns prepare ios`
`tns run ios`

**Comment by chauhan-saurabh** [comment]
after that should I need to update my plist

**Comment by jibon57** [comment]
@chauhan-saurabh I didn't understand you. You will need to add custom url in your `Info.plist` file. Where did you added those line?

**Comment by chauhan-saurabh** [comment]
@jibon57  I am sending  you my plist file and main.ts have a look please


[files.zip](https://github.com/jibon57/nativescript-braintree/files/1331983/files.zip)

**Comment by jibon57** [comment]
@chauhan-saurabh it's `Info.plist` which is located under `app/App_Resources/iOS/Info.plist` not your project's main plist file.

**Comment by chauhan-saurabh** [comment]
ohs @jibon57

**Comment by chauhan-saurabh** [comment]
hello @jibon57 now plugin works fine in IOS but have some issues in android

**Comment by chauhan-saurabh** [comment]
thanks @jibon57 all issues resolved .

**Comment by jibon57** [comment]
Great :)

**Comment by FahadAlbukhari** [comment]
Not working for me.


		<key>UIRequiredDeviceCapabilities</key>
		<array>
			<key>CFBundleURLTypes</key>
			<array>
				<dict>
					<key>CFBundleURLSchemes</key>
					<array>
						<string>com.khd.payments</string>
					</array>
				</dict>
			</array>
			<key>LSApplicationQueriesSchemes</key>
			<array>
				<string>com.venmo.touch.v2</string>
			</array>
			<string>armv7</string>
		</array>



---------------------------------------------------------------
// this import should be first in order to load some required settings (like globals and reflect-metadata)
declare var UIResponder, UIApplicationDelegate, BTAppSwitch;
import { AppModule } from "./app.module";
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import * as app from "application";

if (app.ios) {

  class MyDelegate extends UIResponder {

    public static ObjCProtocols = [UIApplicationDelegate];

    applicationDidFinishLaunchingWithOptions(application, launchOptions): boolean {

      try {

        BTAppSwitch.setReturnURLScheme("com.khd.payments");
        return true;

      } catch (error) {
        console.log(error);
      }

      return false;
    }

    applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {

      try {
        if (url.scheme == "com.khd.payments") {
          BTAppSwitch.handleOpenURLSourceApplication(url, sourceApplication);
          return true;
        }
      } catch (error) {
        console.log(error);
      }

      return false;
    }
  }

  app.ios.delegate = MyDelegate;
}
platformNativeScriptDynamic().bootstrapModule(AppModule);








==============================


Found peer TypeScript 2.4.2
1   0x110ce2bc8 -[TNSRuntime executeModule:referredBy:]
2   0x10ce26e51 main
3   0x113b8bd81 start
4   0x1
JS ERROR reflect-metadata shim is required when using class decorators
07:47:10 - Compilation complete. Watching for file changes.
