### ISSUE TITLE
Braintree Paypal UIResponder issue

### ISSUE THREAD

**Issue by benlooi** [jibon57/nativescript-braintree#13]
Hi.
The instructions for PayPal Venmo implementation creates an issue with my app that is also doing Facebook login (Firebase).

If I include the suggested code for (app.ios), it will cause Facebook login to not redirect back to the app after logging in from Facebook. If I remove the code from my main.ts, the facebook login works fine and returns to my app, but Braintree will fail.

Can you suggest how to allow different URL schemes to be handled for UIResponder or custom app delegate?

Thanks.

**Comment by jibon57** [comment]
@benlooi please post the code that you are using in your `main.ts` file also the link of other plugin.

**Comment by jibon57** [comment]
@benlooi can you try this branch: https://github.com/jibon57/nativescript-braintree/tree/appdelegate ? Let me know if this solve your problem.
