### ISSUE TITLE
Vue - PayPal requires a return URL scheme to be configured

### ISSUE THREAD

**Issue by JuanDeLeon** [jibon57/nativescript-braintree#18]
Hi, I'm working on a Nativescript-Vue project, testing on iOS device, and getting the following error:
[BraintreeSDK] CRITICAL PayPal requires a return URL scheme to be configured via [BTAppSwitch setReturnURLScheme:]. This custom URL scheme must also be registered with your app.

I added the following code at the very top of my main.js file:
```
import { isAndroid, isIOS } from 'tns-core-modules/platform'
import { setupBraintreeAppDeligate } from "nativescript-braintree"

if (isIOS) {
    setupBraintreeAppDeligate("com.mx.lasaves.vue.payments");
}
```

I have added the following to my Info.plist file as well:
```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>com.mx.lasaves.vue.payments</string>
		</array>
	</dict>
</array>
```

The auto-generated Info.plist in my platform folder result is like this:
```
<key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>com.mx.lasaves.vue.payments</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>commxlasavesvue</string>
        </array>
      </dict>
    </array>
<key>CFBundleIdentifier</key>
<string>com.mx.lasaves.vue</string>
```

Any ideas of why I'm still getting that error?
Thanks in advance!

**Comment by JuanDeLeon** [comment]
I hardcoded this line on another plugin I use in my project:
`BTAppSwitch.setReturnURLScheme('com.mx.lasaves.vue.payments');`

Under the `applicationDidFinishLaunchingWithOptions` method, and it worked.
Seems like the `setupBraintreeAppDeligate` is not being called correctly, maybe it should be used differently for Vue?

**Comment by jibon57** [comment]
@JuanDeLeon this mean your other plugin is overriding appdelegate of this plugin. You can have a look this issue https://github.com/jibon57/nativescript-braintree/issues/13 . The other plugin should need to follow the same procedure not to override other plugins' appdelegate.
