### ISSUE TITLE
Issue with Languages in iOS

### ISSUE THREAD

**Issue by Kabyno** [jibon57/nativescript-braintree#19]
Hello, thank you for this plugin! It works perfectly even with Nativescript-vue.
But, something is wrong with languages in iOS, it show only English... I want it in French, no problem with the Android version.

I tried two things:
- Add " pod 'BraintreeDropIn/UIKit' " in nativescript-braintree>platforms>ios>Podfile
- Add CFBundleDevelopmentRegion & CFBundleLocalizations with string "fr" in App_Ressources>iOS>Info.plist

But nothing works, any idea about this? Thank you.

**Comment by jibon57** [comment]
@Kabyno please open issue in `Braintree` repo
