### ISSUE TITLE
BraintreeDropIn 7.5.0 breaks this plugin

### ISSUE THREAD

**Issue by jawa-the-hutt** [jibon57/nativescript-braintree#24]
Looks like [BraintreeDropIn 7.5.0](https://github.com/braintree/braintree-ios-drop-in/releases/tag/7.5.0) will break the compile with Nativescript.  Errors were related to certain colors not being found.  My guess is this is because 7.5.0 introduced IOS Dark mode support.  

Hard setting the Pod version to 7.4.0 inside this plugin' `node_modules/nativescript-braintree/platforms/ios/Podfile` is a temporary workaround.  `pod 'BraintreeDropIn', '7.4.0'`

**Comment by jibon57** [comment]
fixed
