### ISSUE TITLE
IOS App Store UIWebView depreciated - Pod - Braintree/3D-Secure

### ISSUE THREAD

**Issue by jawa-the-hutt** [jibon57/nativescript-braintree#25]
I have submitted an app to the app store and been rejected due to a depreciated API 'UIWebView'.   It looks like this is coming from this plugin and specifically the 3D-Secure Pod from Braintree.

Here's a [link](https://github.com/braintree/braintree_ios/issues/503) to an issue in the Braintree repository. It looks like there is a workaround and new Pod that replaces the 3D-Secure one.  I'm not sure at this point if it's a straight up drop in replacement or if the new Pod will mean portions of this plugin will need adjusted to work with it.  I'm not suing 3D-Secure at all, so I have no real way to test it's functionality for the replacement.

As a temporary work-around I've made adjustments to the Podfile in my local copy and the app store issue is resolved.

Here's my temporary Podfile:
```
pod 'BraintreeDropIn'
pod 'Braintree/Apple-Pay'
pod 'Braintree/PayPal'
pod 'Braintree/Venmo'
#pod 'Braintree/3D-Secure'
pod 'Braintree/PaymentFlow'
pod 'CardIO'
```

**Comment by jibon57** [comment]
thanks
