### ISSUE TITLE
TypeError: ThreeDSecureRequest is not a constructor

### ISSUE THREAD

**Issue by nikolasdas** [jibon57/nativescript-braintree#29]
Hey guys, just tried to run the demo project.
After taping the button I get the above mentioned error from `braintree.android.ts`, line 50.
It seems like `com.braintreepayments.api.dropin.ThreeDSecureRequest` does not exist.
the content of `com.braintreepayments.api.dropin` just seems to be `{ utils: {}, adapters: {}, interfaces: {}, view: {} }`

Any idea?

**Comment by jibon57** [comment]
try
```
tns platform clean android
tns run android 
```

**Comment by jibon57** [comment]
@luke-hawk , will you please have look? In your last pull request I didn't do test. I think it has problem with android in this line:
https://github.com/jibon57/nativescript-braintree/blob/da3652aa41bbaea9d90689fdc84c855e6831933b/src/braintree.android.ts#L49

I think it should need additional dependencies like here: https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#drop-in-ui

**Comment by luke-hawk** [comment]
@jibon57 Sorry, my bad! 🙈 ...I think the additional dependency is only needed for custom UIs. However, 3DS 2 support seems to require Drop-in version 4.3+! So guess we need to bump version in order to make it work
