### ISSUE TITLE
iOS braintree drop-in ui is showing only in english language

### ISSUE THREAD

**Issue by felixkrautschuk** [jibon57/nativescript-braintree#31]
On Android, everything in the drop-in ui is translated correctly (german in my case), but on iOS everything is shown in english only, even if the device has german language.

My config:
- nativescript cli 6.5.0
- nativescript/core 6.5.1
- tns android/ios 6.5.0
- nativescript-braintree 2.0.8

I tested the demo app of this repo. Is there any additional step to make the translations working on iOS?

**Comment by matzefcb** [comment]
Hi, did you find a solution? I'm currently facing the same problem.

**Comment by felixkrautschuk** [comment]
@matzefcb Not sure how to automate this process within the plugin but for now you can copy the <language>.lproj folders from `<Your project>/platforms/ios/Pods/BraintreeDropIn/BraintreeUIKit/Localization/<language>.lproj` to `<Your project>/App_Resources/iOS`. 

Then rebuild the project and the dropin should be shown using the device language.
