### ISSUE TITLE
Not working with latest version of XCode 12.4

### ISSUE THREAD

**Issue by rubenhr** [jibon57/nativescript-braintree#36]
Download latest version of plugin

Environment:
Xcode: 12.4
Nativescript: 7.2.0
Angular: 11

When I tried to run the demo version, not able to run it. Failed when build.

Command: npm run demo.ios

<img width="1607" alt="Screen Shot 2021-02-10 at 20 42 00" src="https://user-images.githubusercontent.com/5392110/107597503-6ff36300-6be0-11eb-90f5-fd34a5abb6b9.png">

**Comment by raedwulf1** [comment]
I am facing the same issue

**Comment by felixkrautschuk** [comment]
@rubenhr @raedwulf1 I believe there is nothing I can do for now.

I guess you are using the latest @nativescript/ios runtime?

Could you try to install @nativescript/ios **7.0.0** and build the app afterwards? (after removing platforms/ios and maybe node_modules as well and run npm install). This seems not to be related to the nativescript-braintree plugin, as I am getting a build error as well for a newly created project and adding a new Podfile to the App_Resources/iOS, just with the following content:

```
platform :ios, '12.0'

pod 'Braintree'
```

(I get not exactly the same error message, but similar)

When I downgrade @nativescript/ios to 7.0.0, I am able to build the project as expected, even with Xcode 12.4, NS 7.2 CLI, latest core-modules etc.

I already created an issue in the ios-v8-runtime repo here: https://github.com/NativeScript/ns-v8ios-runtime/issues/99

**Comment by felixkrautschuk** [comment]
Here is a sample project using latest NS dependencies except @nativescript/ios downgraded to 7.0.0 and the Podfile referencing the Braintree pod. Maybe you can check and confirm that you are able to build that app.

[temp.zip](https://github.com/jibon57/nativescript-braintree/files/5971059/temp.zip)

**Comment by rubenhr** [comment]
Hey Download temp.zip and run, and is throwing an error too. It doesn't work either.

**Comment by felixkrautschuk** [comment]
@rubenhr well, that's strange... can you try to downgrade @nativescript/ios to 7.0.0 in your real project and build that?

**Comment by raedwulf1** [comment]
Hello @felixkrautschuk I've tried that, but it didnt work for me... I got this error: 
![image](https://user-images.githubusercontent.com/30507144/107958004-67e44c00-6f6f-11eb-9741-77118f341fce.png)

**Comment by felixkrautschuk** [comment]
> framework not found ActionSheetPicker_3_0

that seems to be something different

**Comment by rubenhr** [comment]
> Here is a sample project using latest NS dependencies except @nativescript/ios downgraded to 7.0.0 and the Podfile referencing the Braintree pod. Maybe you can check and confirm that you are able to build that app.
> 
> [temp.zip](https://github.com/jibon57/nativescript-braintree/files/5971059/temp.zip)

Hi, 

Here's the sample project with Nativescript 7.0.0 and Podfile adding Braintree.
Can you please try to run and make sure is working for you. Is still failing for me.

[temp.zip](https://github.com/jibon57/nativescript-braintree/files/5982818/temp.zip)

**Comment by felixkrautschuk** [comment]
@rubenhr it is not working for me as well, but I thing this is caused by specifying the Braintree Pod at App_Resources/iOS and using the ns-braintree plugin at the same time.

I removed the Podfile, but there is still a build error, that I have not seen before.
However, when running the demo app of this repo, everything works as expected. I downgraded the @nativescript/ios to 7.0.0 in this repo, maybe you can check the demo app again.

I will see when I can get some time to make some investigations why the demo app is working on my side and your project does not.

**Comment by rubenhr** [comment]
@felixkrautschuk funny thing is that debugging the app/demo works fine, but if you try to release it, then throws errors.
I already downgrade the app to iOS 7 and still having the same issue. Thanks for look at this. Is really important for us.

**Comment by rubenhr** [comment]
@felixkrautschuk Hey, have you tried compiling your solution using webpack. We are using webpack for our app and when get's build is when error is being thrown. I download your demo and it worked, but if you change the reference for your demo to use npm package instead of src, you can see the error. This is becoming really urgent for us. Let me know if we can chat directly or find some time to review this. Thanks again for your support.

**Comment by felixkrautschuk** [comment]
@raedwulf1 @rubenhr sorry for the delayed response, I had no time to work on this problem for several weeks.

I published v.**3.1.0** some minutes ago. I updated the native BraintreeDropin dependencies and was able to build and run the plugin in a separate NativeScript app using the @nativescript/ios 7.3.0 and also 8.0.0, so there should be no need anymore to stick with runtime 7.0.0.

You will need to add the following to your App_Resources/iOS/build.xcconfig:
`IPHONEOS_DEPLOYMENT_TARGET = 12.0;`

I hope that you are also able to successfully run your apps using the latest plugin version.
If you still have problems, feel free to reopen the issue.
