### ISSUE TITLE
iOS and Android Issue with Paypal Payment

### ISSUE THREAD

**Issue by gerardim90** [jibon57/nativescript-braintree#46]
iOS Issue:
I have followed and review twice the instructions for setting up paypal... I see in the logs [BraintreeSDK] CRITICAL PayPal requires a return URL scheme to be configured via [BTAppSwitch setReturnURLScheme:]. This custom URL scheme must also be registered with your app. 
My info.plist has:
                                 <string>fbXXXXXXXXXX</string> (this is for FB login)
				<string>com.googleusercontent.apps.XXXXXXXXXX</string>(this is for google login)
				<string>com.xxxxxx.myasanadiary</string>	
                                 <string>com.xxxxxx.myasanadiary.payments</string>	
				<string>myasanadiary</string>	

I have added the following to the main.ts:
 setupBraintreeAppDeligate("com.xxxxxx.myasanadiary.payments");

Still getting the same. 

Android Issue:
When checking out and selecting paypal... a forever spinner appears and I do not get any feedback on weather there is an issue of not. Any example of manifest.xml and app.gradle I could use.....

Any working  example for nativescript angular I could take a look at. I am currently using nativescript 6.5 and angular 9. Please any help would be really appreciated.

**Comment by felixkrautschuk** [comment]
@gerardim90 what version of the nativescript-braintree plugin did you use? When using the latest version (3.1.0), you should migrate your project to NS 7.

And did you try to run the demo app in this repo? When I run it, everything works as expected for Android and for iOS so please give it a try.

According to your Android issue: I also noticed that once in the past, but without uninstalling and re-installing the app, it was working some hours later, so maybe that is a braintree related issue.

Unfortunately, I have no Angular knowledge so I am not able to provide an Angular sample app right now.

**Comment by gerardim90** [comment]
I ended up solving the issue
