### ISSUE TITLE
Received status code 403 building on Android

### ISSUE THREAD

**Issue by ebiscardi** [jibon57/nativescript-braintree#47]
I get this error when I try to build my app on Android:

`A problem occurred configuring project ':app'.
Could not GET 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden `

It seems linked to this issue on Android SDK:
https://github.com/braintree/braintree_android/issues/293#issuecomment-826870611

The solution is to update the Gradle file like said here:
https://github.com/braintree/braintree_android/issues/293#issuecomment-875644519

**Comment by felixkrautschuk** [comment]
@ebiscardi thanks for the pull-request, I released version **3.1.1** some minutes ago.
