### ISSUE TITLE
disable pay credit card

### ISSUE THREAD

**Issue by NeriCodec** [jibon57/nativescript-braintree#6]
It is possible to do this, to only activate the paypal payment method.

**Comment by jibon57** [comment]
Hi,

I can't see any option to do so: http://www.javadoc.io/doc/com.braintreepayments.api/drop-in/3.3.0

**Comment by NeriCodec** [comment]
Thanks, Apparently there is no way to remove the method of payment by card, is there the possibility of only adding the action of paying with PayPal without using the drop-in with u PaymentButton?

**Comment by jibon57** [comment]
You can give a try this plugin: https://github.com/mkloubert/nativescript-paypal
But that no iOS support
