### ISSUE TITLE
Braintree build failure

### ISSUE THREAD

**Issue by benlooi** [jibon57/nativescript-braintree#8]
Hi. I updated my TNS to 4.2.4, Gradle to 4.10, and SDK to API 28. 
Braintree is not building successfully, throwing error in the Gradle cache appcompat v7 28.0.0-rc02, complaining that AAPT fails, with attr dialogRadiusCorner not found, among other things.

Please help. It was working before, and some of my other plugins require compileSdk higher than 26.

Thank you so much. I would love to contribute to maintaining this but I am not good with Android development. Tried to read your code to find out how to modify for 3 days....

**Comment by jibon57** [comment]
@benlooi change https://github.com/jibon57/nativescript-braintree/blob/eb417000fdf9162ca50ab7ea738c0dc05f0c0061/platforms/android/include.gradle#L15 to
`implementation "com.braintreepayments.api:drop-in:3.6.1"`

**Comment by benlooi** [comment]
Thanks, Solved the issue. I also changed the line after this to:
implementation 'io.card:android-sdk:5.5.1'

**Comment by benlooi** [comment]
Just to add, the plugin will fail if building for Android 28 and above. Need to change the drop-in version to 3.7.1 to fix it.
`implementation "com.braintreepayments.api:drop-in:3.7.1`
